/** Methods and events a skin may use on window.top.controller. */

export const METHOD_ALLOWLIST = Object.freeze([
  'on',
  'off',
  'createSession',
  'createGroup',
  'deleteSession',
  'getRecentSessions',
  'getMessages',
  'getSessionId',
  'getSessionName',
  'setSessionName',
  'updateSessionTimestamp',
  'sendMessage',
  'sendReplyMessage',
  'sendEditMessage',
  'sendFileMessage',
  'forwardMessage',
  'deleteMessage',
  'sendReaction',
  'markRead',
  'sendChatstate',
  'setBlocked',
  'getBlockStatus',
  'fetchBlocklist',
  'pingReachability',
  'callSession',
  'callRemote',
  'videoCallSession',
  'videoCallRemote',
  'acceptCall',
  'rejectCall',
  'endCall',
  'setMute',
  'setHold',
  'transferCall',
  'sendDtmf',
  'switchCamera',
  'changeAudioDevice',
  'getAudioDevices',
  'camera',
  'imagePicker',
  'contactPicker',
  'scanQrCode',
  'startBrowserPairing',
  'stopBrowserPairing',
  'getBrowserPairing',
  'downloadFile',
]);

export const EVENT_ALLOWLIST = Object.freeze([
  'new-message',
  'message-updated',
  'message-reaction',
  'chatstate',
  'receiving-call',
  'ringing',
  'call-started',
  'call-ended',
  'call-connected',
  'call-answered-elsewhere',
  'connecting',
  'video-frame',
  'webrtc-disconnected',
  'mute-state',
  'local-hold-state',
  'active-calls',
  'identity-change',
  'error',
  'block-status',
  'block-result',
  'image-picker-result',
  'inject-remote-id',
  'pairing-status',
  'pairing-ready',
]);

export const CALL_METHODS = Object.freeze([
  'callSession',
  'callRemote',
  'videoCallSession',
  'videoCallRemote',
  'acceptCall',
  'rejectCall',
  'endCall',
  'setMute',
  'setHold',
  'transferCall',
  'sendDtmf',
  'switchCamera',
  'changeAudioDevice',
  'getAudioDevices',
]);

export const OUTPUT_LINT_FORBIDDEN = Object.freeze([
  { id: 'fetch', re: /\bfetch\s*\(/, message: 'Skins must not call fetch(); use arnacon-controller.' },
  { id: 'xhr', re: /\bXMLHttpRequest\b/, message: 'Skins must not use XMLHttpRequest.' },
  { id: 'express', re: /\bexpress\b/i, message: 'Skins must not invent an Express backend.' },
  { id: 'oauth', re: /\boauth\b/i, message: 'Auth is the installed product, not OAuth.' },
  { id: 'mongodb', re: /\b(mongodb|mongoose|postgres|sqlite3)\b/i, message: 'Message history lives in native SQLite, not a generated database.' },
  { id: 'firebase-auth', re: /firebase\s*\.\s*auth/i, message: 'Do not invent Firebase Auth.' },
  { id: 'rest-api', re: /['"`]\/api\//, message: 'Do not invent REST /api/ endpoints.' },
  { id: 'localId-literal', re: /\blocalId\s*=\s*['"`][^'"`]+['"`]/, message: 'Do not invent localId; native injects it at runtime.' },
  { id: 'wallet', re: /\b(ethers\.|web3|walletconnect|metamask)\b/i, message: 'Do not invent a wallet or chain RPC; identity is the installed product.' },
  { id: 'stripe', re: /\bstripe\b/i, message: 'Do not invent payments; Arnacon has no commerce API for skins.' },
]);
